fn_single_line = true
where_single_line = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
normalize_comments = true
reorder_imports = true
reorder_impl_items = true
use_try_shorthand = true
wrap_comments = true
max_width = 99
