[package]
name = "aegir_derive"
description = "Macros for aegir"

version = "0.1.0"
authors = ["Tom Spooner <spooner10000@gmail.com>"]

edition = "2018"

[lib]
name = "aegir_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
